// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.drivinggrpc.driving.rpc.proto.module;

public interface ApplyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.drivinggrpc.driving.rpc.proto.module.ApplyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>bytes picture = 2;</code>
   * @return The picture.
   */
  com.google.protobuf.ByteString getPicture();

  /**
   * <pre>
   *报名日期
   * </pre>
   *
   * <code>string date = 3;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <pre>
   *报名日期
   * </pre>
   *
   * <code>string date = 3;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 5;</code>
   * @return The sex.
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 5;</code>
   * @return The bytes for sex.
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>string age = 6;</code>
   * @return The age.
   */
  java.lang.String getAge();
  /**
   * <code>string age = 6;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>string address = 7;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 7;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string phone = 8;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 8;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string code = 9;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 9;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string old_type = 10;</code>
   * @return The oldType.
   */
  java.lang.String getOldType();
  /**
   * <code>string old_type = 10;</code>
   * @return The bytes for oldType.
   */
  com.google.protobuf.ByteString
      getOldTypeBytes();

  /**
   * <code>string type = 11;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 11;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
