// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.drivinggrpc.driving.rpc.proto.module;

public final class ModuleProto {
  private ModuleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014module.proto\022(com.drivinggrpc.driving." +
      "rpc.proto.module\"\272\001\n\025StatisticsDataReque" +
      "st\022\017\n\007user_id\030\001 \001(\005\022b\n\014request_type\030\002 \001(" +
      "\0162L.com.drivinggrpc.driving.rpc.proto.mo" +
      "dule.StatisticsDataRequest.REQUEST_TYPE\"" +
      ",\n\014REQUEST_TYPE\022\r\n\tSUBJECT_1\020\000\022\r\n\tSUBJEC" +
      "T_4\020\001\"e\n\026StatisticsDataResponse\022\025\n\rnum_q" +
      "uestions\030\001 \001(\t\022\020\n\010accuracy\030\002 \001(\t\022\022\n\naver" +
      "_score\030\003 \001(\t\022\016\n\006degree\030\004 \001(\t\"$\n\021ApplySta" +
      "teRequest\022\017\n\007user_id\030\001 \001(\005\"#\n\022ApplyState" +
      "Response\022\r\n\005state\030\001 \001(\t\"\264\001\n\014ApplyRequest" +
      "\022\017\n\007user_id\030\001 \001(\005\022\017\n\007picture\030\002 \001(\014\022\014\n\004da" +
      "te\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\013\n\003sex\030\005 \001(\t\022\013\n\003a" +
      "ge\030\006 \001(\t\022\017\n\007address\030\007 \001(\t\022\r\n\005phone\030\010 \001(\t" +
      "\022\014\n\004code\030\t \001(\t\022\020\n\010old_type\030\n \001(\t\022\014\n\004type" +
      "\030\013 \001(\t\"\036\n\rApplyResponse\022\r\n\005state\030\001 \001(\t2\267" +
      "\003\n\017ModuleRpcServer\022z\n\005apply\0226.com.drivin" +
      "ggrpc.driving.rpc.proto.module.ApplyRequ" +
      "est\0327.com.drivinggrpc.driving.rpc.proto." +
      "module.ApplyResponse\"\000\022\214\001\n\rgetApplyState" +
      "\022;.com.drivinggrpc.driving.rpc.proto.mod" +
      "ule.ApplyStateRequest\032<.com.drivinggrpc." +
      "driving.rpc.proto.module.ApplyStateRespo" +
      "nse\"\000\022\230\001\n\021getStatisticsData\022?.com.drivin" +
      "ggrpc.driving.rpc.proto.module.Statistic" +
      "sDataRequest\032@.com.drivinggrpc.driving.r" +
      "pc.proto.module.StatisticsDataResponse\"\000" +
      "B9\n(com.drivinggrpc.driving.rpc.proto.mo" +
      "duleB\013ModuleProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_descriptor,
        new java.lang.String[] { "UserId", "RequestType", });
    internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_descriptor,
        new java.lang.String[] { "NumQuestions", "Accuracy", "AverScore", "Degree", });
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyStateResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyRequest_descriptor,
        new java.lang.String[] { "UserId", "Picture", "Date", "Name", "Sex", "Age", "Address", "Phone", "Code", "OldType", "Type", });
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_drivinggrpc_driving_rpc_proto_module_ApplyResponse_descriptor,
        new java.lang.String[] { "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
