// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.drivinggrpc.driving.rpc.proto.module;

public interface StatisticsDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string num_questions = 1;</code>
   * @return The numQuestions.
   */
  java.lang.String getNumQuestions();
  /**
   * <code>string num_questions = 1;</code>
   * @return The bytes for numQuestions.
   */
  com.google.protobuf.ByteString
      getNumQuestionsBytes();

  /**
   * <code>string accuracy = 2;</code>
   * @return The accuracy.
   */
  java.lang.String getAccuracy();
  /**
   * <code>string accuracy = 2;</code>
   * @return The bytes for accuracy.
   */
  com.google.protobuf.ByteString
      getAccuracyBytes();

  /**
   * <code>string aver_score = 3;</code>
   * @return The averScore.
   */
  java.lang.String getAverScore();
  /**
   * <code>string aver_score = 3;</code>
   * @return The bytes for averScore.
   */
  com.google.protobuf.ByteString
      getAverScoreBytes();

  /**
   * <code>string degree = 4;</code>
   * @return The degree.
   */
  java.lang.String getDegree();
  /**
   * <code>string degree = 4;</code>
   * @return The bytes for degree.
   */
  com.google.protobuf.ByteString
      getDegreeBytes();
}
