// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.drivinggrpc.driving.rpc.proto.module;

/**
 * Protobuf type {@code com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest}
 */
public  final class StatisticsDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest)
    StatisticsDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatisticsDataRequest.newBuilder() to construct.
  private StatisticsDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatisticsDataRequest() {
    requestType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatisticsDataRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StatisticsDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            requestType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.class, com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.Builder.class);
  }

  /**
   * <pre>
   *枚举消息类型
   * </pre>
   *
   * Protobuf enum {@code com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE}
   */
  public enum REQUEST_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *proto3版本中，首成员必须为0，成员不应有相同的值
     * </pre>
     *
     * <code>SUBJECT_1 = 0;</code>
     */
    SUBJECT_1(0),
    /**
     * <code>SUBJECT_4 = 1;</code>
     */
    SUBJECT_4(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *proto3版本中，首成员必须为0，成员不应有相同的值
     * </pre>
     *
     * <code>SUBJECT_1 = 0;</code>
     */
    public static final int SUBJECT_1_VALUE = 0;
    /**
     * <code>SUBJECT_4 = 1;</code>
     */
    public static final int SUBJECT_4_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static REQUEST_TYPE valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static REQUEST_TYPE forNumber(int value) {
      switch (value) {
        case 0: return SUBJECT_1;
        case 1: return SUBJECT_4;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<REQUEST_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        REQUEST_TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<REQUEST_TYPE>() {
            public REQUEST_TYPE findValueByNumber(int number) {
              return REQUEST_TYPE.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final REQUEST_TYPE[] VALUES = values();

    public static REQUEST_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private REQUEST_TYPE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE)
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private int userId_;
  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  public int getUserId() {
    return userId_;
  }

  public static final int REQUEST_TYPE_FIELD_NUMBER = 2;
  private int requestType_;
  /**
   * <pre>
   * </pre>
   *
   * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  public int getRequestTypeValue() {
    return requestType_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
   * @return The requestType.
   */
  public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE getRequestType() {
    @SuppressWarnings("deprecation")
    com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE result = com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE.valueOf(requestType_);
    return result == null ? com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0) {
      output.writeInt32(1, userId_);
    }
    if (requestType_ != com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE.SUBJECT_1.getNumber()) {
      output.writeEnum(2, requestType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, userId_);
    }
    if (requestType_ != com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE.SUBJECT_1.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, requestType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest)) {
      return super.equals(obj);
    }
    com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest other = (com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (requestType_ != other.requestType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (37 * hash) + REQUEST_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + requestType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest)
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.class, com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.Builder.class);
    }

    // Construct using com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0;

      requestType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataRequest_descriptor;
    }

    @java.lang.Override
    public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest getDefaultInstanceForType() {
      return com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest build() {
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest buildPartial() {
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest result = new com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest(this);
      result.userId_ = userId_;
      result.requestType_ = requestType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest) {
        return mergeFrom((com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest other) {
      if (other == com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.getDefaultInstance()) return this;
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (other.requestType_ != 0) {
        setRequestTypeValue(other.getRequestTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 user_id = 1;</code>
     * @return The userId.
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private int requestType_ = 0;
    /**
     * <pre>
     * </pre>
     *
     * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
     * @param value The enum numeric value on the wire for requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeValue(int value) {
      requestType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
     * @return The requestType.
     */
    public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE getRequestType() {
      @SuppressWarnings("deprecation")
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE result = com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE.valueOf(requestType_);
      return result == null ? com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
     * @param value The requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestType(com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      requestType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestType() {
      
      requestType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest)
  }

  // @@protoc_insertion_point(class_scope:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest)
  private static final com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest();
  }

  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatisticsDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<StatisticsDataRequest>() {
    @java.lang.Override
    public StatisticsDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StatisticsDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StatisticsDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatisticsDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

