// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.drivinggrpc.driving.rpc.proto.module;

/**
 * Protobuf type {@code com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse}
 */
public  final class StatisticsDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse)
    StatisticsDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatisticsDataResponse.newBuilder() to construct.
  private StatisticsDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatisticsDataResponse() {
    numQuestions_ = "";
    accuracy_ = "";
    averScore_ = "";
    degree_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatisticsDataResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StatisticsDataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            numQuestions_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            accuracy_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            averScore_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            degree_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse.class, com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse.Builder.class);
  }

  public static final int NUM_QUESTIONS_FIELD_NUMBER = 1;
  private volatile java.lang.Object numQuestions_;
  /**
   * <code>string num_questions = 1;</code>
   * @return The numQuestions.
   */
  public java.lang.String getNumQuestions() {
    java.lang.Object ref = numQuestions_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      numQuestions_ = s;
      return s;
    }
  }
  /**
   * <code>string num_questions = 1;</code>
   * @return The bytes for numQuestions.
   */
  public com.google.protobuf.ByteString
      getNumQuestionsBytes() {
    java.lang.Object ref = numQuestions_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      numQuestions_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCURACY_FIELD_NUMBER = 2;
  private volatile java.lang.Object accuracy_;
  /**
   * <code>string accuracy = 2;</code>
   * @return The accuracy.
   */
  public java.lang.String getAccuracy() {
    java.lang.Object ref = accuracy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accuracy_ = s;
      return s;
    }
  }
  /**
   * <code>string accuracy = 2;</code>
   * @return The bytes for accuracy.
   */
  public com.google.protobuf.ByteString
      getAccuracyBytes() {
    java.lang.Object ref = accuracy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accuracy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVER_SCORE_FIELD_NUMBER = 3;
  private volatile java.lang.Object averScore_;
  /**
   * <code>string aver_score = 3;</code>
   * @return The averScore.
   */
  public java.lang.String getAverScore() {
    java.lang.Object ref = averScore_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      averScore_ = s;
      return s;
    }
  }
  /**
   * <code>string aver_score = 3;</code>
   * @return The bytes for averScore.
   */
  public com.google.protobuf.ByteString
      getAverScoreBytes() {
    java.lang.Object ref = averScore_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      averScore_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEGREE_FIELD_NUMBER = 4;
  private volatile java.lang.Object degree_;
  /**
   * <code>string degree = 4;</code>
   * @return The degree.
   */
  public java.lang.String getDegree() {
    java.lang.Object ref = degree_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      degree_ = s;
      return s;
    }
  }
  /**
   * <code>string degree = 4;</code>
   * @return The bytes for degree.
   */
  public com.google.protobuf.ByteString
      getDegreeBytes() {
    java.lang.Object ref = degree_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      degree_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNumQuestionsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, numQuestions_);
    }
    if (!getAccuracyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accuracy_);
    }
    if (!getAverScoreBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, averScore_);
    }
    if (!getDegreeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, degree_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNumQuestionsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, numQuestions_);
    }
    if (!getAccuracyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accuracy_);
    }
    if (!getAverScoreBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, averScore_);
    }
    if (!getDegreeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, degree_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse)) {
      return super.equals(obj);
    }
    com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse other = (com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse) obj;

    if (!getNumQuestions()
        .equals(other.getNumQuestions())) return false;
    if (!getAccuracy()
        .equals(other.getAccuracy())) return false;
    if (!getAverScore()
        .equals(other.getAverScore())) return false;
    if (!getDegree()
        .equals(other.getDegree())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUM_QUESTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getNumQuestions().hashCode();
    hash = (37 * hash) + ACCURACY_FIELD_NUMBER;
    hash = (53 * hash) + getAccuracy().hashCode();
    hash = (37 * hash) + AVER_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getAverScore().hashCode();
    hash = (37 * hash) + DEGREE_FIELD_NUMBER;
    hash = (53 * hash) + getDegree().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse)
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse.class, com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse.Builder.class);
    }

    // Construct using com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      numQuestions_ = "";

      accuracy_ = "";

      averScore_ = "";

      degree_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.drivinggrpc.driving.rpc.proto.module.ModuleProto.internal_static_com_drivinggrpc_driving_rpc_proto_module_StatisticsDataResponse_descriptor;
    }

    @java.lang.Override
    public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse getDefaultInstanceForType() {
      return com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse build() {
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse buildPartial() {
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse result = new com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse(this);
      result.numQuestions_ = numQuestions_;
      result.accuracy_ = accuracy_;
      result.averScore_ = averScore_;
      result.degree_ = degree_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse) {
        return mergeFrom((com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse other) {
      if (other == com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse.getDefaultInstance()) return this;
      if (!other.getNumQuestions().isEmpty()) {
        numQuestions_ = other.numQuestions_;
        onChanged();
      }
      if (!other.getAccuracy().isEmpty()) {
        accuracy_ = other.accuracy_;
        onChanged();
      }
      if (!other.getAverScore().isEmpty()) {
        averScore_ = other.averScore_;
        onChanged();
      }
      if (!other.getDegree().isEmpty()) {
        degree_ = other.degree_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object numQuestions_ = "";
    /**
     * <code>string num_questions = 1;</code>
     * @return The numQuestions.
     */
    public java.lang.String getNumQuestions() {
      java.lang.Object ref = numQuestions_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        numQuestions_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string num_questions = 1;</code>
     * @return The bytes for numQuestions.
     */
    public com.google.protobuf.ByteString
        getNumQuestionsBytes() {
      java.lang.Object ref = numQuestions_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numQuestions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string num_questions = 1;</code>
     * @param value The numQuestions to set.
     * @return This builder for chaining.
     */
    public Builder setNumQuestions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      numQuestions_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string num_questions = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumQuestions() {
      
      numQuestions_ = getDefaultInstance().getNumQuestions();
      onChanged();
      return this;
    }
    /**
     * <code>string num_questions = 1;</code>
     * @param value The bytes for numQuestions to set.
     * @return This builder for chaining.
     */
    public Builder setNumQuestionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      numQuestions_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accuracy_ = "";
    /**
     * <code>string accuracy = 2;</code>
     * @return The accuracy.
     */
    public java.lang.String getAccuracy() {
      java.lang.Object ref = accuracy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accuracy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accuracy = 2;</code>
     * @return The bytes for accuracy.
     */
    public com.google.protobuf.ByteString
        getAccuracyBytes() {
      java.lang.Object ref = accuracy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accuracy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accuracy = 2;</code>
     * @param value The accuracy to set.
     * @return This builder for chaining.
     */
    public Builder setAccuracy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accuracy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accuracy = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccuracy() {
      
      accuracy_ = getDefaultInstance().getAccuracy();
      onChanged();
      return this;
    }
    /**
     * <code>string accuracy = 2;</code>
     * @param value The bytes for accuracy to set.
     * @return This builder for chaining.
     */
    public Builder setAccuracyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accuracy_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object averScore_ = "";
    /**
     * <code>string aver_score = 3;</code>
     * @return The averScore.
     */
    public java.lang.String getAverScore() {
      java.lang.Object ref = averScore_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        averScore_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string aver_score = 3;</code>
     * @return The bytes for averScore.
     */
    public com.google.protobuf.ByteString
        getAverScoreBytes() {
      java.lang.Object ref = averScore_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        averScore_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string aver_score = 3;</code>
     * @param value The averScore to set.
     * @return This builder for chaining.
     */
    public Builder setAverScore(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      averScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string aver_score = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAverScore() {
      
      averScore_ = getDefaultInstance().getAverScore();
      onChanged();
      return this;
    }
    /**
     * <code>string aver_score = 3;</code>
     * @param value The bytes for averScore to set.
     * @return This builder for chaining.
     */
    public Builder setAverScoreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      averScore_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object degree_ = "";
    /**
     * <code>string degree = 4;</code>
     * @return The degree.
     */
    public java.lang.String getDegree() {
      java.lang.Object ref = degree_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        degree_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string degree = 4;</code>
     * @return The bytes for degree.
     */
    public com.google.protobuf.ByteString
        getDegreeBytes() {
      java.lang.Object ref = degree_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        degree_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string degree = 4;</code>
     * @param value The degree to set.
     * @return This builder for chaining.
     */
    public Builder setDegree(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      degree_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string degree = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDegree() {
      
      degree_ = getDefaultInstance().getDegree();
      onChanged();
      return this;
    }
    /**
     * <code>string degree = 4;</code>
     * @param value The bytes for degree to set.
     * @return This builder for chaining.
     */
    public Builder setDegreeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      degree_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse)
  }

  // @@protoc_insertion_point(class_scope:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse)
  private static final com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse();
  }

  public static com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatisticsDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<StatisticsDataResponse>() {
    @java.lang.Override
    public StatisticsDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StatisticsDataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StatisticsDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatisticsDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.drivinggrpc.driving.rpc.proto.module.StatisticsDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

