// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.drivinggrpc.driving.rpc.proto.module;

public interface StatisticsDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <pre>
   * </pre>
   *
   * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  int getRequestTypeValue();
  /**
   * <pre>
   * </pre>
   *
   * <code>.com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE request_type = 2;</code>
   * @return The requestType.
   */
  com.drivinggrpc.driving.rpc.proto.module.StatisticsDataRequest.REQUEST_TYPE getRequestType();
}
