// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.drivinggrpc.driving.rpc.proto.user;

public interface registerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.drivinggrpc.driving.rpc.proto.user.registerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string state = 1;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 1;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();
}
