// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.drivinggrpc.driving.rpc.proto.user;

public interface setUserMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.drivinggrpc.driving.rpc.proto.user.setUserMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>bytes head_image = 2;</code>
   * @return The headImage.
   */
  com.google.protobuf.ByteString getHeadImage();

  /**
   * <code>string nick_name = 3;</code>
   * @return The nickName.
   */
  java.lang.String getNickName();
  /**
   * <code>string nick_name = 3;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <pre>
   *签名
   * </pre>
   *
   * <code>string signature = 4;</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <pre>
   *签名
   * </pre>
   *
   * <code>string signature = 4;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <code>int32 minute = 5;</code>
   * @return The minute.
   */
  int getMinute();

  /**
   * <pre>
   *报名日期
   * </pre>
   *
   * <code>string date = 6;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <pre>
   *报名日期
   * </pre>
   *
   * <code>string date = 6;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string name = 7;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 7;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string phone = 8;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 8;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string sex = 9;</code>
   * @return The sex.
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 9;</code>
   * @return The bytes for sex.
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>string age = 10;</code>
   * @return The age.
   */
  java.lang.String getAge();
  /**
   * <code>string age = 10;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>string job = 11;</code>
   * @return The job.
   */
  java.lang.String getJob();
  /**
   * <code>string job = 11;</code>
   * @return The bytes for job.
   */
  com.google.protobuf.ByteString
      getJobBytes();

  /**
   * <code>string qq_code = 12;</code>
   * @return The qqCode.
   */
  java.lang.String getQqCode();
  /**
   * <code>string qq_code = 12;</code>
   * @return The bytes for qqCode.
   */
  com.google.protobuf.ByteString
      getQqCodeBytes();

  /**
   * <code>string we_chat = 13;</code>
   * @return The weChat.
   */
  java.lang.String getWeChat();
  /**
   * <code>string we_chat = 13;</code>
   * @return The bytes for weChat.
   */
  com.google.protobuf.ByteString
      getWeChatBytes();

  /**
   * <code>string e_mail = 14;</code>
   * @return The eMail.
   */
  java.lang.String getEMail();
  /**
   * <code>string e_mail = 14;</code>
   * @return The bytes for eMail.
   */
  com.google.protobuf.ByteString
      getEMailBytes();

  /**
   * <code>string new_head_image = 15;</code>
   * @return The newHeadImage.
   */
  java.lang.String getNewHeadImage();
  /**
   * <code>string new_head_image = 15;</code>
   * @return The bytes for newHeadImage.
   */
  com.google.protobuf.ByteString
      getNewHeadImageBytes();

  /**
   * <code>string old_head_image = 16;</code>
   * @return The oldHeadImage.
   */
  java.lang.String getOldHeadImage();
  /**
   * <code>string old_head_image = 16;</code>
   * @return The bytes for oldHeadImage.
   */
  com.google.protobuf.ByteString
      getOldHeadImageBytes();
}
